version: '3'
services:
  web:
    build: .
    ports:
        - "8000:4000"
    volumes:
        - .:/code     
    links:
        - postgres
    depends_on:
        - postgres
    environment:
        - ENVIRONMENT=development   
    
  postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=geheim
      volumes:
          - ./postgresql/data:/var/lib/postgresql/data